# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='p_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
