# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0005_auto_20170922_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20)),
                ('t_age', models.IntegerField(blank=True, null=True)),
                ('t_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.Student')),
            ],
        ),
    ]
