# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_auto_20170922_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_color', models.CharField(blank=True, max_length=10, null=True)),
                ('phant_color', models.CharField(blank=True, max_length=10, null=True)),
                ('shirt_size', models.IntegerField(blank=True, null=True)),
                ('phant_size', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.Student')),
            ],
        ),
    ]
