# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_uniform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='student',
        ),
    ]
