# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_auto_20170923_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='houseName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
