# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_auto_20170925_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.Student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
