# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_auto_20170929_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='houseName',
        ),
        migrations.AddField(
            model_name='parents',
            name='p_email',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
