# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0015_auto_20171008_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='standard',
            new_name='student',
        ),
    ]
