# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0017_auto_20171008_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='student',
            new_name='name',
        ),
    ]
