# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0019_auto_20171008_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='t_subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=12, null=True),
        ),
    ]
