# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0020_auto_20171008_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('r_password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
